### ISSUE TITLE
请教下lordofpomelo的问题

### ISSUE THREAD

**Issue by hw233** [NextZeus/pomeloandpm2#1]
现在官方最新的lordofpomelo demo和你改的那个demo都不能正常运行，能不能麻烦你把你的这个lordofpomelo更新到直接安装就可以运行，因为之前是搞c++、python方面的，对nodejs还不是太熟,希望得到你的解答。

**Comment by NextZeus** [comment]
@hw233  如果运行有什么问题可以把问题抛出来一块看下怎么解决，那个仓库不打算再做更新了。

**Comment by hw233** [comment]
用你的这个demo在game-server下运行只有这两行日志       

                                                           
 [2017-12-14 22:51:23.908] [INFO] pomelo - [/root/nodejs/lordofpomelo_bak/game-server/node_modules/pomelo/lib/application.js] application inited: "master-server-1"

[2017-12-14 22:51:24.133] [INFO] console - [data sync component] load mapping file done.               
 
如果果官方的demo注册账号没问题，但登陆会有个这样的错误  
                                                    
 `[2017-12-14 22:56:26.656] [INFO] console - [2017-12-14 22:56:26.655] [ERROR] pomelo-rpc - [mqtt-acceptor] process rpc message error TypeError: callback is not a function
    at Object.create (/Users/zqb/Desktop/lab/nodejs/pomelo/lordofpomelo_neteasy/game-server/app/dao/mysql/dao-pool.js:18:4)
    at Pool._createResource (/Users/zqb/Desktop/lab/nodejs/pomelo/lordofpomelo_neteasy/game-server/node_modules/generic-pool/lib/Pool.js:279:42)
    at Pool._dispense (/Users/zqb/Desktop/lab/nodejs/pomelo/lordofpomelo_neteasy/game-server/node_modules/generic-pool/lib/Pool.js:210:12)
    at Pool.acquire (/Users/zqb/Desktop/lab/nodejs/pomelo/lordofpomelo_neteasy/game-server/node_modules/generic-pool/lib/Pool.js:410:10)
    at Object.NND.query (/Users/zqb/Desktop/lab/nodejs/pomelo/lordofpomelo_neteasy/game-server/app/dao/mysql/mysql.js:24:8)
    at Object.userDao.getUserById (/Users/zqb/Desktop/lab/nodejs/pomelo/lordofpomelo_neteasy/game-server/app/dao/userDao.js:207:29)
    at Remote.pro.auth (/Users/zqb/Desktop/lab/nodejs/pomelo/lordofpomelo_neteasy/game-server/app/servers/auth/remote/authRemote.js:40:10)
    at Dispatcher.pro.route (/Users/zqb/Desktop/lab/nodejs/pomelo/lordofpomelo_neteasy/game-server/node_modules/pomelo-rpc/lib/rpc-server/dispatcher.js:52:10)
    at Acceptor.cb (/Users/zqb/Desktop/lab/nodejs/pomelo/lordofpomelo_neteasy/game-server/node_modules/pomelo-rpc/lib/rpc-server/gateway.js:22:16)
    at processMsg (/Users/zqb/Desktop/lab/nodejs/pomelo/lordofpomelo_neteasy/game-server/node_modules/pomelo-rpc/lib/rpc-server/acceptors/mqtt-acceptor.js:138:12)

[2017-12-14 22:56:26.658] [INFO] console - [2017-12-14 22:56:26.657] [WARN] pomelo-rpc - [mqtt-mailbox] timer is not exsits, serverId: connector-server-1 remote: undefined, host: 127.0.0.1, port: 3650

[2017-12-14 22:56:29.561] [ERROR] pomelo - [/Users/zqb/Desktop/lab/nodejs/pomelo/lordofpomelo_neteasy/game-server/node_modules/pomelo/lib/filters/handler/timeout.js] request "connector.entryHandler.entry" timeout.

[2017-12-14 22:56:56.565] [INFO] console - [2017-12-14 22:56:56.564] [ERROR] pomelo-rpc - [mqtt-mailbox] rpc connector-server-1 callback timeout 30000, remote server 0 host: 127.0.0.1, port: 3650

[2017-12-14 22:56:56.565] [INFO] console - [2017-12-14 22:56:56.565] [ERROR] pomelo-rpc - [MailStation] [pomelo-rpc] fail to send message Error: rpc connector-server-1 callback timeout 30000, remote server 0 host: 127.0.0.1, port: 3650
    at Timeout.<anonymous> (/Users/zqb/Desktop/lab/nodejs/pomelo/lordofpomelo_neteasy/game-server/node_modules/pomelo-rpc/lib/rpc-client/mailboxes/mqtt-mailbox.js:257:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

[2017-12-14 22:56:56.566] [INFO] console - [2017-12-14 22:56:56.566] [ERROR] pomelo-rpc - [failprocess] rpc failed with error, remote server: auth-server-1, msg: {"namespace":"user","serverType":"auth","service":"authRemote","method":"auth","args":["54336e7af8f79e4543882121ffed004c"]}, error code: 5
`                                                                                                                                                                     希望能得到你的帮助能把这个demo跑起来，node 7,8,9版本我都有试过，应该是某个插件版本导致的，如果交流不方便的话可否告诉个你的联系方式我加下你

**Comment by NextZeus** [comment]
1. 我的demo，把上面你遇到的官方的mysql的问题修复了。 归根结底是mysql 的第三方库升级导致原有的方法不能正常使用了。 
2. 你只说明了log的问题，不清楚你使用我的demo是否能正常登录？

**Comment by NextZeus** [comment]
方便的话，加下微信聊吧 hautlixiaodong
